In [20]:
class sphere:
    pi=3.14
    def __init__(self,radius):
        self.radius=radius
    def area(self):
        return 4*(sphere.pi)*(self.radius*self.radius)
    def volume(self):
        return (4/3)*sphere.pi*(self.radius**3)

In [25]:
a=sphere(1)

In [26]:
a.area

<bound method sphere.area of <__main__.sphere object at 0x7f016c134198>>

In [27]:
a.area()    

12.56

In [28]:
a.volume()

4.1866666666666665

In [1]:
def genarators(start,stop):
    while start<=stop:
        yield start
        start+=1

In [2]:
num=genarators(1,10)

In [3]:
num

<generator object genarators at 0x7efd903577d8>

In [4]:
print(num)

<generator object genarators at 0x7efd903577d8>


In [5]:
list(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
def s(x):
    print(x**3)

In [15]:
s(3)

27


In [16]:
x,y=1,2

In [17]:
x

1

In [19]:
def power(x,n=2):
    return x**n

In [21]:
power(3,n=3)

27

In [23]:
import numpy as np

In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a[:,1]

array([2, 5, 8])

In [29]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [30]:
a[1:,:2]

array([[4, 5],
       [7, 8]])

In [31]:
a>4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [32]:
a[a>4]

array([5, 6, 7, 8, 9])

In [33]:
np.where(a>2)

(array([0, 1, 1, 1, 2, 2, 2]), array([2, 0, 1, 2, 0, 1, 2]))

In [58]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [36]:
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [38]:
c=np.arange(1,10)

In [39]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.square(c)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [45]:
a.sum()

45

In [46]:
a.sum(axis=0)

array([12, 15, 18])

In [47]:
a.sum(axis=1)

array([ 6, 15, 24])

In [48]:
a.mean()

5.0

In [50]:
a.mean(axis=0)

array([4., 5., 6.])

In [51]:
a.mean(axis=1)

array([2., 5., 8.])

In [52]:
a.min()

1

In [53]:
a.max()

9

In [55]:
a.min(axis=0)

array([1, 2, 3])

In [56]:
a.max(axis=1)

array([3, 6, 9])

In [57]:
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [62]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
d=np.array([1,2,3])
e=np.array([2,3,4])

In [68]:
c=d.copy()

In [69]:
print(c)

[1 2 3]


In [71]:
c[0]=10

In [72]:
c

array([10,  2,  3])

In [73]:
d

array([1, 2, 3])